; Items
melee_mainhand := "j"
excalibur := "k"
sgb := "l"
mainhand := "]"
offhand := "["
shield := "\"
helm := "l"
body := "."
legs := "/"
boots := "8"
flank := "o"
melee_2h := "h"

; Abilities
bladed_dive := "3"
ingen := "5"
smoke_cloud := "H"
mage_prayer := "Ins"
ranged_prayer := "Home"
hybrid_prayer := "H"
swap := "="
disrupt := "0"
venge := "9"
deto := "D"
omni := "Y"
special_attack := "6"
auto := ":"
surge := "1"
eof := "u"
wild_magic := "A"